### ISSUE TITLE
How can i change the cloud_controller_ng's timezone?

### ISSUE THREAD

**Issue by ybshen** [cloudfoundry/cf-release#1064] opened 2016-09-23 04:59 UTC
When is create an app,i found the app's createdAt is incorrect.I already change the vm's timezone and ccdb's timezone.

**Comment by dsabeti** [comment] 2016-09-26 20:04
@ybshen As far as I can tell, all timestamps are given in UTC. [This](https://github.com/cloudfoundry/cloud_controller_ng/blob/173954d8ed2d2b9624d074ba2b277f7bd47c8432/lib/cloud_controller.rb#L21) looks like the code and [this](https://github.com/cloudfoundry/cloud_controller_ng/blob/ac38c2795112adc6eff1fb9ef7bdb85773786f51/spec/unit/lib/db/db_session_settings_spec.rb#L4) looks like the spec for it.

@SocalNick, do you have any information about how the cloud controller manages timestamps / timezones?

**Comment by Gerg** [comment] 2016-09-27 17:03
It looks like we are storing these timestamps in UTC and returning them on the API in UTC. This seems like the correct behavior from an API perspective, since we do not know the local timezone of the client. Clients can choose to localize their timezones if they wish.

**Comment by dsabeti** [comment] 2016-09-27 18:11
@ybshen I asked the CLI team about this, and it seems that the CLI doesn't really support localizing your timezone on the client side. But, they did suggest that you request a feature by creating an issue on their github repo. You can do so here: https://github.com/cloudfoundry/cli/issues

In general, I agree with the idea that the client should localize timezones instead of the server. Since you have a course of action with the CLI team, I'm going to close this github issue. But if you have further concerns or questions feel free to re-open the issue.

**Closed by dsabeti** 2016-09-27 18:11 UTC
Labels: unscheduled

**Comment by ybshen** [comment] 2016-09-28 11:13
Thanks.But it is not CLI problem.I create an app.I found the app's created_at metadata in ccdb is not local timezone.How can i change it to local timezone?

**Comment by ybshen** [comment] 2016-09-28 11:14
@dsabeti @dsabeti @Gerg Thanks.But it is not CLI problem.I create an app.I found the app's created_at metadata in ccdb is not local timezone.How can i change it to local timezone?

**Comment by dsabeti** [comment] 2016-09-28 19:00
Hi @ybshen. Sorry if our previous communication wasn't clear. It is not currently possible to change it to the local timezone. The cloud controller and the database use UTC by design to guarantee that timestamps are consistent for all users, regardless of their timezone.

You can always submit a feature request [by opening an issue in the cloud controller repo itself](https://github.com/cloudfoundry/cloud_controller_ng/issues). It is unlikely that the cloud controller will ever support configuring the timezone of the database itself because it will lead to complications with internal logic of the cloud controller, as well as confusing timestamps for users in other timezones. There is a chance that they could implement a change where the cloud controller _presents_ the timestamp in the desired timezone for requests through the API. But that is up to @SocalNick to prioritize, and the team has other pressing concerns.
