### ISSUE TITLE
Started Instances reported incorrectly

### ISSUE THREAD

**Issue by omazhary** [cloudfoundry/cf-release#1002] opened 2016-07-05 11:13 UTC
After running acceptance tests, it intermittently occurs that the number of instances for an app are reported as ```?``` instead of an actual number:
```
Getting apps in org myOrg / space mySpace as admin...
OK

name    requested state   instances   memory   disk   urls
myApp    started          ?/1         64M      1G     <url>
```
So far, the current workaround used is to simply restart the consul_agent on a malfunctioning hm9000 node running. However, it is not still clear why it is malfunctioning.

**Comment by srinat999** [comment] 2016-07-06 13:00
Hey, I also faced this issue. For me the problem was with DNS setup. My public API endpoint (api..), doppler and hm9000 wasn't getting resolved correctly. After fixing that, it worked. Hope that helps

**Comment by Amit-PivotalLabs** [comment] 2016-07-06 17:52
Hi @omazhary 

What made you think to restart the consul_agent?  Were there any logs that showed something failing that led you to decide to do that?

**Comment by omazhary** [comment] 2016-07-07 09:14
There wasn't anything weird in the logs at all. I just wanted to restart the hm9000 nodes, and I wound up getting failing processes on each one. So, I decided to just restart the consul_agent, to force the services to re-register with it again.

Looking back on @srinat999's comment, it might have had something to do with DNS. According to the [consul description](https://github.com/cloudfoundry-incubator/consul-release#within-cloudfoundry).

**Comment by Amit-PivotalLabs** [comment] 2016-07-08 20:41
@omazhary did @srinat999's fix also work for you?

**Comment by omazhary** [comment] 2016-07-10 10:31
I didn't have time to test it. But I think it could be related, since restarting the consul agents re-registers the components' DNS names.

**Comment by omazhary** [comment] 2016-07-11 07:35
Did an ```nslookup``` on the api node, resolves back to the router. Makes sense. Still, however, cannot reproduce the problem to tell if @srinat999's fix will solve it.

**Comment by Amit-PivotalLabs** [comment] 2016-07-12 04:12
Consul DNS is used for internal service discovery.  Typically nothing that Consul DNS resolves should resolve back to the router.  I will close this issue for now, but do let us know if you're able to reproduce it.

**Closed by Amit-PivotalLabs** 2016-07-12 04:12 UTC
Labels: in progress
