### ISSUE TITLE
Hold off on adding releases until notes are ready

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-release#782] opened 2015-09-09 22:31 UTC
One of the great things about GitHub releases is that watchers get notified and the release notes go out in the email. The v217 release seems to be a blank template. Perhaps hold off from submitting release until notes are written up?

Thanks for the releases with great notes!
Nic

**Comment by Amit-PivotalLabs** [comment] 2015-09-21 19:30
Thanks @drnic 

Sounds good, let me take some time and think about how best to do this.

**Comment by Amit-PivotalLabs** [comment] 2015-09-23 01:42
@drnic this issue should be resolved for the next release, v219 (barring some exceptional situations).  v218 is currently in Draft mode too, but I suspect it started out in Published mode and someone manually switched it to Draft.

See https://github.com/Amit-PivotalLabs/mega-pm-tools/commit/47dce1fdfc940824225e41d920135b50967ddd15 and https://mega.ci.cf-app.com/pipelines/release

I will close this for now, if the issue is not resolved next time around, please let me know.

**Closed by Amit-PivotalLabs** 2015-09-23 01:42 UTC

**Comment by drnic** [comment] 2015-09-23 02:13
Thanks Amit for coming up with a solution!




Is your plan to have draft releases manually written; and concourse converts them?

**Comment by Amit-PivotalLabs** [comment] 2015-09-23 02:19
Nope, a human will convert them.  All PMs are automatically given stories
to contribute to the release notes.  In theory, something could publish the
draft once all those stories are accepted, but for now it's still manual.
