### ISSUE TITLE
Error dialing trafficcontroller server: websocket: bad handshake.

### ISSUE THREAD

**Issue by ericper** [cloudfoundry/cf-release#1132] opened 2016-12-28 19:59 UTC
When doing a cf logs \<appname\>, I get the following:

_Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.system.luxoft-pcf.com:443)._

I am using cf CLI  v6.22 and Elastic Runtime v1.8.21 build 1 (hosted on AWS).

In searching through the Ops Manager logs for loggregator_trafficcontroller and doppler jobs, I observe the following:
in **loggregator_trafficcontroller.stdout:**
_loggregator_trafficcontroller/loggregator/src/trafficcontroller/channel_group_connector/channel_group_connector.go","line":89,"method":"trafficcontroller/channel_group_connector.(*ChannelGroupConnector).connectToServer"}
{"timestamp":1482813696.437145233,"process_id":6394,"source":"loggregator trafficcontroller","log_level":"error","message":"websocket handler: Not a websocket handshake: websocket: could not find connection header with token 'upgrade'","data":null,"file":"/var/vcap/data/compile/_

in **metron_agent.stderr.log:**
_2016/12/28 19:13:29 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)_

in **metron_agent_lograte_cron:**
_error: error renaming temp state file /var/lib/logrotate/status.tmp_

Steps taken to troubleshoot:
In AWS Console kill the loggregator_trafficcontroller and dopler jobs and have the Ops Manager auto restart them. No luck!

Anyone?

**Comment by JesseTAlford** [comment] 2016-12-29 00:48
@ericper, it sounds like you're using a commercial distribution of cloud foundry (Pivotal's Elastic Runtime Ops Manager tile in PCF). I recommend you contact Pivotal's support. I'm guessing you have some manner of misconfiguration, but the configuration context of such a distribution is radically different from cf-releases's manifest generation process.

**Comment by ericper** [comment] 2016-12-29 18:56
Thanks @JesseTAlford. You are correct, it is a commercial distribution and we have reached out to PCF Support. I was reaching out proactively to cf-release, just in case someone else had run into the problem elsewhere and discovered a fix for it.

**Comment by dsabeti** [comment] 2017-01-04 18:42
@ericper Any news on this? If there's something actionable on the OSS side, I'd like to prioritize the work. Otherwise, I'd like to close the issue. Just let me know.

**Comment by ericper** [comment] 2017-01-04 20:41
@dsabeti Please either close this issue out or reprioritize it. I plan to get support from the vendor directly and will circle back for help if needed. Thank you!

**Comment by dsabeti** [comment] 2017-01-04 20:43
Great, I'll close the issue.

**Closed by dsabeti** 2017-01-04 20:43 UTC
Labels: unscheduled

**Comment by GeekyTex** [comment] 2018-03-02 17:38
Old post, but I ran into the same problem and found this issue via Google search. To anyone else who lands here, the problem is you have to override the loggregator port to 4443 in Ops Manager (In the "Network" settings) when deploying PCF on AWS. 

It's in the documentation, but as a one-liner and easy it's to miss.

**Comment by genevieve** [comment] 2018-03-21 18:53
If you are using cf-deployment, there is an ops-file for this on aws: `cf-deployment/operations/aws.yml`

**Comment by ashwithahn** [comment] 2018-07-19 04:32
I am running into same issue from CF cli "cf version 6.36.1+e3799ad7e.2018-04-04"
Could somebody please help me with same error seen when checking **cf nozzle --debug**
WEBSOCKET REQUEST
GET /firehose/FirehosePlugin? HTTP/1.1
Host: wss://doppler.app-cloudfoundry.com:443
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: [HIDDEN]
Origin: wss://doppler.app-cloudfoundry.com:443
Authorization: **deleted for posting here**
WEBSOCKET RESPONSE
HTTP/1.1 400 Bad Request
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: a84e96f7-820e-41d9-4a14-0ed6134a8625
Content-Length: 12
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Thu, 19 Jul 2018 04:27:16 GMT
Sec-Websocket-Version: 13

Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.app-cloudfoundry.com:443).

Seems like port issue, please help me change the port for doppler or any other solution?
