### ISSUE TITLE
Error 400007: 'runner_z1/0 [...] ' is not running after update.

### ISSUE THREAD

**Issue by rdoerr01** [cloudfoundry/cf-release#1194] opened 2017-04-25 20:48 UTC
After running "bosh deploy" all the VM's come up and are running, but then it starts doing the update of the VM's.  It is with error 400007 for runner_z1.  This is for a vshpere install with the latest code for a few days ago.

+--------+--------------+--------------------------------------------------+--------------+
| Name   | Release(s)   | Stemcell(s)                                      | Cloud Config |
+--------+--------------+--------------------------------------------------+--------------+
| cf-env | cf/257+dev.1 | bosh-vsphere-esxi-ubuntu-trusty-go_agent/3363.19 | none         |
+--------+--------------+--------------------------------------------------+--------------+

Both warden and dea_next were failing after the update.
+----------------------------------------------------------------------------+---------+-----+-----------+-----------------+
| runner_z1/0 (4bfb3e7c-e14b-44ed-a293-72f4030df5f3)*                        | failing | n/a | runner_z1 | 192.168.105.135 |
|   consul_agent                                                             | running |     |           |                 |
|   warden                                                                   | unknown |     |           |                 |
|   dea_next                                                                 | unknown |     |           |                 |
|   dir_server                                                               | running |     |           |                 |
|   dea_logging_agent                                                        | running |     |           |                 |
|   metron_agent                                                             | running |     |           |                 |
 
Login to runner_z1 to look at logs files.
		monit summary
runner_z1/0ebd53b3-7916-46d6-8bf4-38c154889551:~# monit summary
The Monit daemon 5.2.5 uptime: 1h 32m 

Process 'consul_agent'              running
Process 'warden'                    not monitored
Process 'dea_next'                  not monitored
Process 'dir_server'                running
Process 'dea_logging_agent'         running
Process 'metron_agent'              running
System 'system_localhost'           running

	cat /var/vcap/sys/log/warden_ctl.err.log
runner_z1/4bfb3e7c-e14b-44ed-a293-72f4030df5f3:/var/vcap/sys/log# cat warden_ctl.err.log
[2017-04-25 19:28:56+0000] ------------ STARTING warden_ctl at Tue Apr 25 19:28:56 UTC 2017 --------------
[2017-04-25 19:29:07+0000] sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory
[2017-04-25 19:31:29+0000] ------------ STARTING warden_ctl at Tue Apr 25 19:31:29 UTC 2017 --------------
[2017-04-25 19:31:29+0000] sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory

		cat /var/vcap/sys/log/dea_ctl.err.log
runner_z1/4bfb3e7c-e14b-44ed-a293-72f4030df5f3:/var/vcap/sys/log# cat /var/vcap/sys/log/dea_ctl.err.log
[2017-04-25 19:30:56+0000] ------------ STARTING dea_ctl at Tue Apr 25 19:30:56 UTC 2017 --------------
[2017-04-25 19:30:56+0000] /var/vcap/jobs/dea_next/bin/dea_ctl: line 69: /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory
[2017-04-25 19:33:29+0000] ------------ STARTING dea_ctl at Tue Apr 25 19:33:29 UTC 2017 --------------
[2017-04-25 19:33:29+0000] /var/vcap/jobs/dea_next/bin/dea_ctl: line 69: /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory

I'm new to all this cloud foundry stuff, but I do have bosh-init working and though I had most of this until I ran into this error.  This looks to be out of my control from anything that I put in the cf-stub.yml file.

Thanks

Ray

**Comment by cppforlife** [comment] 2017-04-25 23:40
@rdoerr01 3363.19 fully disables ipv6 (https://github.com/cloudfoundry/bosh/releases/tag/stable-3363.19). i believe you will have to switch to 3312.x stemcell line that does not have this backport.

**Comment by dsabeti** [comment] 2017-04-25 23:46
Hey @rdoerr01. This is a recently found bug caused by updating to stemcell version 3363.19. We have [a story to fix this](https://www.pivotaltracker.com/story/show/144071355).

In the meantime, you should try using the stemcell 3312.X series (the latest is [3312.23](https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3312.23)). 

Alternatively -- and this is what I'd really suggest -- you could deploy [Diego](https://github.com/cloudfoundry/diego-release) instead of the DEAs, because we're going to stop supporting the DEAs in about a month.

Let me know if that helps.

**Comment by dsabeti** [comment] 2017-04-25 23:46
Oh @cppforlife Beat me to the punch.

**Comment by rdoerr01** [comment] 2017-04-26 12:55
@cppforlife @dsabeti Thanks guys, that did the trick.  The latest was now 3312.24, so I took a chance and tried that, and it completed fine.  As for doing a setup with Diego instead of the DEA's, the manifest template files for sphere that I've found only have a version using DEA.  If I had a complete manifest template, I would surely give it a try, but right now I would just love to finally be able to deploy something within CF after spending a week o this.  All the Cert's required by this setup and the 30 VM's it created on VMware is a little crazy to be able to understand CF and how it works.

Thanks

Ray

**Comment by dsabeti** [comment] 2017-04-26 17:38
Yeah, the cert stuff is a little crazy. You might want to take a look at [this doc that describes the certificates](https://github.com/cloudfoundry/cf-release/blob/master/on-tls-certificates.md) -- it's not much but hopefully it helps people understand how to manage their certs.

As for Diego, it [also has a manifest generation script](https://github.com/cloudfoundry/diego-release/blob/develop/scripts/generate-deployment-manifest). Like I said, the DEA support will end May 22, so it's in your best interest to try it out soon.

**Comment by dsabeti** [comment] 2017-04-27 17:25
@rdoerr01, I'm going to close this issue since it seems like you've figured out what you need. But feel free to re-open if you have any other questions.

**Closed by dsabeti** 2017-04-27 17:25 UTC
Labels: unscheduled
