### ISSUE TITLE
traffic controller- dial error (read tcp i/o timeout)

### ISSUE THREAD

**Issue by abhikco** [cloudfoundry/cf-release#1038] opened 2016-08-16 08:55 UTC
After setting up Cloud Foundry on Bosh Lite, “cf push” and “cf logs” for a node.js application fails.
My configurations are shown below:

```
root@bosh-lite:/home/vagrant/cf-abacus# bosh target
Current target is https://192.168.50.4:25555 (Bosh Lite Director)

root@bosh-lite:/home/vagrant/cf-abacus# bosh vms
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'
Deployment 'cf-warden'

Director task 27

Task 27 done

+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs          |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (783dc4f2-b18f-40a9-b1b4-6f76306c7a26)                           | running | n/a | large_z1  | 10.244.0.138 |
| blobstore_z1/0 (3d691827-5e49-4117-a381-2187e35886c4)                     | running | n/a | medium_z1 | 10.244.0.130 |
| consul_z1/0 (7fc7b3a9-9fcc-4d9c-977a-decfe863419e)                        | running | n/a | small_z1  | 10.244.0.54  |
| doppler_z1/0 (14680e42-c726-44e9-80ca-6e27bebc5a23)                       | running | n/a | medium_z1 | 10.244.0.146 |
| etcd_z1/0 (15a26ca3-b14b-44a5-a977-5b3036574564)                          | running | n/a | medium_z1 | 10.244.0.42  |
| ha_proxy_z1/0 (5ee32052-6f3d-4191-8abe-4d6a428aaf39)                      | running | n/a | router_z1 | 10.244.0.34  |
| hm9000_z1/0 (ab545dff-41ca-4927-882d-e0e5bb73f487)                        | running | n/a | medium_z1 | 10.244.0.142 |
| loggregator_trafficcontroller_z1/0 (eca6a918-9e05-4ddc-ab92-519f0c26dd26) | running | n/a | small_z1  | 10.244.0.150 |
| nats_z1/0 (026d423b-30b6-411b-87df-17cc46861664)                          | running | n/a | medium_z1 | 10.244.0.6   |
| postgres_z1/0 (245cb81c-f2e6-43dc-9098-ff8e960b7b3a)                      | running | n/a | medium_z1 | 10.244.0.30  |
| router_z1/0 (12e87356-c4d1-4683-b0fe-0c4e38e4149d)                        | running | n/a | router_z1 | 10.244.0.22  |
| runner_z1/0 (15b4c464-1d35-4792-af0d-6aad11b2bca1)                        | running | n/a | runner_z1 | 10.244.0.26  |
| uaa_z1/0 (a8e76f1b-4dcd-4581-8011-d7e0349de27b)                           | running | n/a | medium_z1 | 10.244.0.134 |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+

VMs total: 13

root@bosh-lite:/home/vagrant/cf-abacus# cf api              
API endpoint: https://api.bosh-lite.com (API version: 2.59.0)
```

While pushing the application, the errors I get are:

```
root@bosh-lite:/home/vagrant/cf-abacus# cf logs abacus-usage-aggregator –recent

2016-08-15T12:08:55.06+0000 [API/0]      OUT Updated app with guid 0b3b9d74-3ded-40d3-b6f0-e19a8def0f73 ({"name"=>"abacus-usage-aggregator", "instances"=>1, "memory"=>512, "disk_quota"=>512, "environment_json"=>"PRIVATE DATA HIDDEN"})
2016-08-15T12:09:33.28+0000 [API/0]      OUT Updated app with guid 0b3b9d74-3ded-40d3-b6f0-e19a8def0f73 ({"state"=>"STOPPED"})
2016-08-15T12:09:48.84+0000 [DEA/0]      OUT Got staging request for app with id 0b3b9d74-3ded-40d3-b6f0-e19a8def0f73
2016-08-15T12:09:48.85+0000 [API/0]      OUT Updated app with guid 0b3b9d74-3ded-40d3-b6f0-e19a8def0f73 ({"state"=>"STARTED"})
2016-08-15T12:09:50.52+0000 [STG/0]      OUT -----> Downloaded app package (1.8M)
2016-08-15T12:24:50.58+0000 [STG/0]      ERR
2016-08-15T12:24:50.58+0000 [STG/0]      OUT
2016-08-15T12:24:50.74+0000 [API/0]      ERR Encountered error: Stager error: failed to stage application:
2016-08-15T12:24:50.74+0000 [API/0]      ERR Script exited with status 255
```

After turning on ```CF_TRACE```, the error messages are:

```
Warning: error tailing logs
Error dialing traffic controller server: read tcp 10.244.0.33:38578->10.244.0.34:443: i/o timeout.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.bosh-lite.com:443).
```

Please note that the system is behind a proxy and the proxy environment variables are all set properly. 
I restarted the loggregator traffic controller VM to see if it helps but to no avail.

**Comment by abhikco** [comment] 2016-08-16 23:27
The bosh deployment and release info:

```
root@bosh-lite:/home/vagrant/cf-release/bosh-lite/deployments# bosh deployments
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'

+-----------+--------------+----------------------------------------------------+--------------+
| Name      | Release(s)   | Stemcell(s)                                        | Cloud Config |
+-----------+--------------+----------------------------------------------------+--------------+
| cf-warden | cf/240+dev.1 | bosh-warden-boshlite-ubuntu-trusty-go_agent/3262.2 | none         |
+-----------+--------------+----------------------------------------------------+--------------+

Deployments total: 1
root@bosh-lite:/home/vagrant/cf-release/bosh-lite/deployments# bosh releases
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'

+------+------------+-------------+
| Name | Versions   | Commit Hash |
+------+------------+-------------+
| cf   | 240+dev.1* | 1b88d9e4    |
+------+------------+-------------+
(*) Currently deployed

Releases total: 1

```

**Comment by APShirley** [comment] 2016-08-23 16:59
Hi @abhikco,

Can you please submit your deployment manifest (please replace any real credentials with`REDACTED`) so we can help you debug your issue? Additionally if you are using an app manifest for the app you are pushing could you please submit that as well?

Thanks,

Al && @jaresty

**Comment by abhikco** [comment] 2016-08-24 09:53
[cf.zip](https://github.com/cloudfoundry/cf-release/files/434432/cf.zip)

The deployment manifest is attached herewith. 
I deployed the cf-abacus applications with the steps described here: 
https://github.com/cloudfoundry-incubator/cf-abacus#deploying-to-cloud-foundry 

Thanks,
Abhik

**Comment by DennisDenuto** [comment] 2016-08-30 21:52
Hello @abhikco 

Thanks for uploading your manifest. We diffed it against a properly generated bosh-lite manifest for cf v240 and didn't see any differences, so the problem isn't your deployment manifest.

We think the problem might be with your bosh-lite setup -- with your proxy setup, for example. 
We don't think any proxy environment variables are required when you are ssh'd onto the bosh-lite vagrant vm. Can you re-try without the `https_proxy` env variable?
  
In the meantime, we're going to bring in help from the bosh team. @cppforlife Do you have any ideas?

Thanks
Dennis && @dsabeti

**Comment by jaresty** [comment] 2016-10-13 19:28
@abhikco Is this still an issue for you? It's been over a month since there's been activity on this issue, so we'd like to close it.

**Comment by ChunyiLyu** [comment] 2016-10-19 23:08
We're considering this issue closed; please feel free to re-open it or raise another if you still need help.

**Closed by ChunyiLyu** 2016-10-19 23:08 UTC
Labels: scheduled

**Comment by vivekzhere** [comment] 2016-11-04 10:16
I am also facing the same issue after updating my bosh lite setup to CF release v245. My system is also behind a proxy and the proxy variables are set properly. I had to rollback my setup to the older cf-release version to get logs working again.

**Comment by jaresty** [comment] 2016-11-16 20:18
@vivekzhere We will follow up with you on your issue #1093
