### ISSUE TITLE
doppler_z1/0  is not running after update while upgrading CF 245 to CF 247

### ISSUE THREAD

**Issue by Pratibha-28** [cloudfoundry/cf-release#1120] opened 2016-12-07 14:36 UTC
We are upgrading CF 245 to CF 247. 
Below is content of doppler.stderr.log
```
panic: sync cluster failed

goroutine 1 [running]:
panic(0xa4b880, 0xc420179de0)
        /var/vcap/data/packages/golang1.7/48ce7b3927e6f7e6576fff21a7dc9d22b7ba9c62.1-480f6b2b56fd74dae43c759f446a536929b6d2ee/src/runtime/panic.go:500 +0x1a1
main.NewStoreAdapter(0xc42011c1e0, 0xe, 0xc42011be78)
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:55 +0x1c1
main.main()
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:87 +0x20c
panic: sync cluster failed

goroutine 1 [running]:
panic(0xa4b880, 0xc4201c5e00)
        /var/vcap/data/packages/golang1.7/48ce7b3927e6f7e6576fff21a7dc9d22b7ba9c62.1-480f6b2b56fd74dae43c759f446a536929b6d2ee/src/runtime/panic.go:500 +0x1a1
main.NewStoreAdapter(0xc42016a1e0, 0xe, 0xc420169e78)
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:55 +0x1c1
main.main()
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:87 +0x20c
panic: sync cluster failed

goroutine 1 [running]:
panic(0xa4b880, 0xc4201cbe00)
        /var/vcap/data/packages/golang1.7/48ce7b3927e6f7e6576fff21a7dc9d22b7ba9c62.1-480f6b2b56fd74dae43c759f446a536929b6d2ee/src/runtime/panic.go:500 +0x1a1
main.NewStoreAdapter(0xc4201701e0, 0xe, 0xc42016fe78)
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:55 +0x1c1
main.main()
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:87 +0x20c
panic: sync cluster failed
```

Below is content of doppler.stdout.log
```
{"timestamp":1481107227.804125547,"process_id":5102,"source":"doppler","log_level":"info","message":"Startup: Setting up the doppler server","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/doppler/main.go","line":87,"method":"main.main"}
{"timestamp":1481107227.869140625,"process_id":5102,"source":"doppler","log_level":"info","message":"Listening for GRPC connections on 8082","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/doppler/doppler.go","line":133,"method":"main.New"}
{"timestamp":1481107227.869291544,"process_id":5102,"source":"doppler","log_level":"info","message":"WebsocketServer: Listening for sinks at :8081","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/doppler/sinkserver/websocketserver/websocket_server.go","line":84,"method":"doppler/sinkserver/websocketserver.New"}
{"timestamp":1481107227.869376659,"process_id":5102,"source":"doppler","log_level":"info","message":"Startup: doppler server started.","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/doppler/main.go","line":99,"method":"main.main"}
{"timestamp":1481107227.869759321,"process_id":5102,"source":"doppler","log_level":"info","message":"Starting Open File Descriptor Monitor...","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/monitor/openfd.go","line":32,"method":"monitor.(*LinuxFileDescriptor).Start"}
{"timestamp":1481107227.869950771,"process_id":5102,"source":"doppler","log_level":"info","message":"Starting FD monitor with pid 5102","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/monitor/openfd.go","line":34,"method":"monitor.(*LinuxFileDescriptor).Start"}
{"timestamp":1481107227.870274305,"process_id":5102,"source":"doppler","log_level":"info","message":"UDP listener listening on port 10.0.2.51:3457","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/doppler/listeners/udp_listener.go","line":44,"method":"doppler/listeners.(*UDPListener).Start"}
{"timestamp":1481107227.870408535,"process_id":5102,"source":"doppler","log_level":"info","message":"TCP listener listening on 10.0.2.51:3458","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/doppler/listeners/tcp_listener.go","line":124,"method":"doppler/listeners.(*TCPListener).Start"}
{"timestamp":1481113690.802530289,"process_id":5102,"source":"doppler","log_level":"error","message":"AppStoreWatcher: Got error while waiting for ETCD events: EOF","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/github.com/cloudfoundry/loggregatorlib/store/app_service_store_watcher.go","line":89,"method":"github.com/cloudfoundry/loggregatorlib/store.(*AppServiceStoreWatcher).Run"}
{"timestamp":1481113690.902903080,"process_id":5102,"source":"doppler","log_level":"error","message":"AppStoreWatcher: Got error while waiting for ETCD events: store request timed out","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/github.com/cloudfoundry/loggregatorlib/store/app_service_store_watcher.go","line":89,"method":"github.com/cloudfoundry/loggregatorlib/store.(*AppServiceStoreWatcher).Run"}
{"timestamp":1481113691.003449202,"process_id":5102,"source":"doppler","log_level":"error","message":"AppStoreWatcher: Got error while waiting for ETCD events: store request timed out","data":null,"file":"/var/vcap/data/compile/doppler/loggregator/src/github.com/cloudfoundry/loggregatorlib/store/app_service_store_watcher.go","line":89,"method":"github.com/cloudfoundry/loggregatorlib/store.(*AppServiceStoreWatcher).Run"}
```

**Comment by dsabeti** [comment] 2016-12-08 22:58
@wfernandes @ahevenor This looks like a doppler issue. Could someone from the Loggregator team take a look at this?

**Comment by ahevenor** [comment] 2016-12-08 23:29
@dsabeti I duplicated as https://www.pivotaltracker.com/story/show/135818391 for our backlog and will review in our next IPM.

**Comment by apoydence** [comment] 2016-12-13 18:34
"sync cluster failed" is an error from the store adapter (etcd client) when it is [unable to connect to the etcd cluster](https://github.com/cloudfoundry/storeadapter/blob/ea0ac938c99c4316c557a3cd8ad4c9a1db1a6d95/etcdstoreadapter/etcd_store_adapter.go#L109). This implies the etcd cluster is unhealthy.

**Comment by dsabeti** [comment] 2016-12-13 22:11
Thanks @apoydence. I'm going to re-open the issue so we can help debug the etcd problem.

@Pratibha-28 Could you upload your etcd logs?

@evanfarrar Could someone from the CF Infrastructure team help out here?

**Comment by dsabeti** [comment] 2017-01-04 18:32
@Pratibha-28 Is this still an issue for you? If not, I'd like to close the issue. Otherwise, I'll try to rope in the right engineers to help you.

**Comment by mhoran** [comment] 2017-01-19 15:14
@dsabeti we've seen this twice now on the Greenhouse team. The only way to resolve has been to tear down our entire environment and stand up again. We're not seeing any issues with other etcd components.

**Comment by dsabeti** [comment] 2017-01-20 22:22
@mhoran, let's rope in the infrastructure team, since the conversation seemed to end at problems with etcd.

@evanfarrar @christianang, could we get your help debugging this?

**Comment by christianang** [comment] 2017-01-23 23:37
@mhoran @Pratibha-28 I've been trying to reproduce, did an upgrade from 245 to 247 and could not get etcd to fail yet. If you do see it fail again could you upload any etcd logs, that might help track down the issue.

Also is etcd running in tls mode? Is etcd not failing when doppler fails?

The etcd vm colocates an `etcd_consistency_checker` job which starts failing if etcd is split brained. It is pretty interesting that etcd did not fail if it did split brain on rolling etcd, but doppler received a `sync cluster failed`. So I want to say etcd did not split brain and there is some sort of communication problem between doppler and etcd, but I can't say definitively without logs.

Thanks,
Christian

**Comment by dsabeti** [comment] 2017-02-22 22:35
Hey all, is this still an issue people are seeing in their deployments? If there's still a problem, I'd like to keep the conversation moving and drive for a solution. Otherwise, I'd like to close the issue. I'll close this out at the end of the week.

**Comment by dsabeti** [comment] 2017-03-09 04:17
Closing due to inactivity.

**Closed by dsabeti** 2017-03-09 04:17 UTC
Labels: unscheduled
