### ISSUE TITLE
UAA failing to start in minimalistic deployment --Could not resolve placeholder 'login.serviceProviderKey' --

### ISSUE THREAD

**Issue by kikiya** [cloudfoundry/cf-release#1116] opened 2016-12-05 11:54 UTC
The deployment is failing on uaa_z1. 

![screen shot 2016-12-05 at 6 48 47 am](https://cloud.githubusercontent.com/assets/4748696/20883993/ede1d20e-bab6-11e6-839a-6bccf1b3a5e7.png)

The logs are showing some missing login info, and I can't see any discrepancies in the minimal yml.
Here is a snippet of the log, 
```
[2016-12-05 11:31:40.641] uaa - 12094 [localhost-startStop-1] ....  WARN --- XmlWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"
[2016-12-05 11:31:40.647] uaa - 12094 [localhost-startStop-1] .... ERROR --- DispatcherServlet: Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:223)
```

The full logs attached here - 
[uaa.log.zip](https://github.com/cloudfoundry/cf-release/files/630947/uaa.log.zip)

**Comment by dsabeti** [comment] 2016-12-08 23:18
Hi @kikiya. Let's see what we can do to start debugging.

1. Which version of cf-release are you deploying?
1. Please upload your deployment manifest **with any sensitive data such as password and private keys redacted**

Thanks,
David

**Comment by kikiya** [comment] 2016-12-09 16:04
Hello @dsabeti thanks for responding. 

I'm using the "latest" cf-release. In the minimal yml I have all the releases as "latest" 

I have uploaded the deployment manifest. I left the keys which were in the example yml only removing the one I generated. I changed the file extension to allow for upload. Basically, I'm using the same manifest here - https://github.com/cloudfoundry/cf-release/blob/master/example_manifests/minimal-aws.yml Only adding to that my subnet info, availability zone, elastic ip, and my generated keys. 
[minimal-aws.txt](https://github.com/cloudfoundry/cf-release/files/642611/minimal-aws.txt)

Thanks again,
kiki

**Comment by fhanik** [comment] 2016-12-09 16:28
We've been asked to not provide any default keys anymore. The 

login.saml.serviceProviderKey
login.saml.serviceProviderKeyPassword
login.saml.serviceProviderKeyCertificate

as well as the default JWT signing keys were removed

**Comment by kikiya** [comment] 2016-12-09 16:31
thanks @fhanik I'll try the deployment again and update this post. should the minimal-aws.yml on github be updated?

**Comment by fhanik** [comment] 2016-12-09 16:35
@kikiya I have to check if we can update it, the mandate was 'to not supply any default keys' to users

**Comment by fhanik** [comment] 2016-12-09 16:36
@kikiya so you have to supply those values yourself

**Comment by kikiya** [comment] 2016-12-09 16:43
@fhanik I see. There are a few other default keys that are still in that example manifest. Maybe the documentation should be updated to reflect the steps for creating those values. 

For example this step (https://github.com/cloudfoundry/cf-release/tree/master/example_manifests):

>Generate a SSL certificate for your System Domain
Run "openssl genrsa -out cf.key 1024"
Run "openssl req -new -key cf.key -out cf.csr"
For the Common Name, you must enter "*." followed by your System Domain
Run "openssl x509 -req -in cf.csr -signkey cf.key -out cf.crt"
Run "cat cf.crt && cat cf.key" and replace REPLACE_WITH_SSL_CERT_AND_KEY with this value.

Are you saying we need to follow that for the saml tokens as well?

**Comment by fhanik** [comment] 2016-12-09 16:48
there are some tools in the cf-release package to generate x509 certs

https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-uaa-certs

**Comment by dsabeti** [comment] 2016-12-09 19:13
@kikiya @fhanik I think this issue is resolved on the `develop` branch: https://github.com/cloudfoundry/cf-release/blob/develop/example_manifests/minimal-aws.yml#L342-L398.

`minimal-aws.yml` is an example manifest and shouldn't be used for a production environment, so we feel comfortable putting in default keys and passwords. 

@kikiya, if you want to use this manifest in a secure way, you'll have to generate your own cert and key and replace the default one in the manifest. Also, you'll have to use the `develop` branch of cf-release (instead of `master`).

Let us know if you manage to get this deployed.

**Comment by kikiya** [comment] 2016-12-09 19:16
okay, let me first try this dev branch version. 

I tore down the entire environment to start over, and destroyed my bosh controller in the process. I'll restart with as soon as all my pre-reqs are in place and let you know. 

BTW, I am using it only for development and evaluation so I'm okay with the defaults for now. 

Thanks again for this. @dsabeti

**Comment by dsabeti** [comment] 2017-01-04 18:29
@kikiya I'm going to close this issue since it sounds like you got what you needed. If you need anything else related to this, feel free to reopen this issue.

**Closed by dsabeti** 2017-01-04 18:29 UTC
Labels: unscheduled

**Comment by jshingler** [comment] 2017-01-24 21:11
I recommend reopening this issue or opening a related issue to correct the documentation on the github UAA site.

**Comment by fhanik** [comment] 2017-01-24 21:14
Tracked by https://www.pivotaltracker.com/story/show/138270091

**Comment by jshingler** [comment] 2017-01-24 23:27
Awesome That is what I am trying todo.  without additional info it is unusable.  

Also, needs to be updated for running locally

**Comment by kikiya** [comment] 2017-01-24 23:39
This will eventually prove to be very useful in the getting started
process.

I struggled quite a bit before reaching out.

Thanks!

**Comment by karungithub** [comment] 2017-03-16 20:42
Hi,
Please pardon me if I am posting under an incorrect issue. I am trying to push the UAA app into PWS according to the instructions specified at http://docs.pivotal.io/pivotalcf/1-9/concepts/architecture/uaa.html  and I am running into the following issue.
uccessfully destroyed container
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:141)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:82)
2017-03-16T15:46:01.61-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:220)

I would really appreciate if someone can help with what needs to be done here to fix this issue.

Thanks,

**Comment by dsabeti** [comment] 2017-03-16 20:51
@karungithub 

This looks like the same problem (not having `login.serviceProviderKey` configured correctly), but the deployment is pretty different. This repository is concerned with deploy _Cloud Foundry_ using _BOSH_; you're trying to deploy _UAA_ using the _cf CLI_.

No problem though: you can just as easily ask for help by opening an issue on the [UAA repo](https://github.com/cloudfoundry/uaa) -- you'll get help from the UAA team about the workflow you're using.

**Comment by karungithub** [comment] 2017-03-16 21:00
Thanks @dsabeti. I will open an issue on UAA repo.
