### ISSUE TITLE
open files limit on gorouter

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/cf-release#614] opened 2015-02-11 07:56 UTC
As I see in [code][1], router should be able to open 100K connections. But it can open only 4K.

As root:
```
# ulimit -Hn  
4096
```

As vcap:
```
$ ulimit -Hn  
4096
```

My environment: CF v192, stemcell 2719.3.

[1]: http://bit.ly/1zK7KsJ

**Comment by sykesm** [comment] 2015-02-11 12:19
If you want to check the actual, enforced, active limit of a process, cat /proc/:pid/limits and look at the output.

The script that launches the router explicitly sets the limit to 100K: https://github.com/cloudfoundry/cf-release/blob/v198/jobs/gorouter/templates/gorouter_ctl.erb#L60

When I check the limits on a machine, it reflects that configuration:

```
root@735486a0-f0d1-45f8-b78c-f2bb1eca1fb2:/var/vcap/jobs/gorouter# monit status
The Monit daemon 5.2.4 uptime: 23h 32m 

Process 'gorouter'
  status                            running
  monitoring status                 monitored
  pid                               119
  parent pid                        1
  uptime                            19h 57m 
  children                          10
  memory kilobytes                  15756
  memory kilobytes total            21452
  memory percent                    0.2%
  memory percent total              0.3%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Wed Feb 11 12:19:20 2015

Process 'metron_agent'
  status                            running
  monitoring status                 monitored
  pid                               166
  parent pid                        1
  uptime                            19h 57m 
  children                          2
  memory kilobytes                  12764
  memory kilobytes total            12764
  memory percent                    0.2%
  memory percent total              0.2%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Wed Feb 11 12:19:20 2015

System 'system_735486a0-f0d1-45f8-b78c-f2bb1eca1fb2'
  status                            running
  monitoring status                 monitored
  load average                      [0.47] [0.37] [0.30]
  cpu                               1.5%us 1.0%sy 0.1%wa
  memory usage                      2811712 kB [46.0%]
  swap usage                        179272 kB [8.5%]
  data collected                    Wed Feb 11 12:19:20 2015

root@735486a0-f0d1-45f8-b78c-f2bb1eca1fb2:/var/vcap/jobs/gorouter# cat /proc/119/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              8388608              bytes     
Max core file size        0                    0                    bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             1024                 1024                 processes 
Max open files            100000               100000               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       1024                 1024                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
root@735486a0-f0d1-45f8-b78c-f2bb1eca1fb2:/var/vcap/jobs/gorouter# 
```

Looks like it's working as intended.

**Comment by lexsys27** [comment] 2015-02-11 15:14
I have checked the process limits and they are ok. But I still can't open more than 2K connections to my application: gorouter reports 4K opened connections (2K in and 2K out) and refuses to open more.

I will do some addition investigation and write update here.

**Comment by crhino** [comment] 2015-02-24 22:19
@lexsys27 It looks like you figured out the problem [here](https://groups.google.com/a/cloudfoundry.org/forum/?utm_medium=email&utm_source=footer#!msg/vcap-dev/Swr3vd3jUoY/Sqs2JIr0qdcJ), we are going to close this issue.

Cheers,
@crhino & @luan, CF Runtime Team

**Closed by crhino** 2015-02-24 22:19 UTC
